spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: library
  security:
    user:
      password: password
  mvc:
    log-request-details: true
  application:
    name: libraryapp

server:
  port: 5000

logging:
  level:
    org:
      springframework:
        web: DEBUG
        data:
          mongodb: DEBUG
jwt:
  secret: mySuperSecretKeyWithEnoughLength!

embeddings:
  source: ${EMBEDDING_SOURCE:serverlessEndpoint}
openai:
  base-url: https://api.openai.com
  model: text-embedding-3-small
  api-key: ${OPENAI_KEY:yourKey}
vertex:
  base-url: https://us-central1-aiplatform.googleapis.com
  model: multimodalembedding@001
  project-id: ${VERTEX_PROJECT_ID:yourProjectId}
  api-key: ${VERTEX_KEY:yourKey}
voyage:
  base-url: https://api.voyageai.com/v1
  model: voyage-3-large
  output-dimension: 2048
  api-key: ${VOYAGE_KEY:yourKey}
serverlessEndpoint:
  base-url: https://us-central1-projectphoenix-verteximage.cloudfunctions.net